main: net.craftcitizen.imagemaps.ImageMaps
author: SydMontague
version: ${project.version}
api-version: 1.13
name: ImageMaps
commands:
    imagemap:
        description: ImageMaps plugin commands, place images on walls
        permission-message: You do not have permission to use this command.
        usage: |
          /imagemap place <filename> [frameVisible] [frameFixed] [frameGlowing] [size] - starts image placement
          /imagemap download <filename> <sourceURL> - downloads an image
          /imagemap delete <filename> - deletes an image
          /imagemap info <filename> - displays image info
          /imagemap reload <filename> - reloads an image from disk
          /imagemap list [page] - lists all files in the images folder
          /imagemap help [command] - shows help
permissions:
    imagemaps.*:
        default: true
        children:
          imagemaps.place: true
          imagemaps.download: true
          imagemaps.delete: true
          imagemaps.info: true
          imagemaps.list: true
          imagemaps.reload: true
          imagemaps.help: true
          imagemaps.toggleFixed: true
          imagemaps.toggleVisible: true
    imagemaps.place:
        default: true
    imagemaps.download:
        default: true
    imagemaps.delete:
        default: true
    imagemaps.info:
        default: true
    imagemaps.list:
        default: true
    imagemaps.reload:
        default: true
    imagemaps.help:
        default: true
    imagemaps.toggleFixed:
        default: true
    imagemaps.toggleVisible:
        default: true
